apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hafu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pbvs-tenant/rhtap-demo-app/hacbs-test-project-hafu@sha256:ab6de1f6201f0e303d8a27a34eceddb0930f29828e64ffa8173bfb0828531157
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
